### ISSUE TITLE
mm穿不上sx装备掉落不了sx装备

### ISSUE THREAD

**Issue by 3393525847** [Saukiya/SX-Item#13]
这是报错
[15:39:32 ERROR]: Could not pass event MythicMobSpawnEvent to SX-Item v3.2.4
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
        at io.lumine.xikage.mythicmobs.mobs.MythicMob.spawn(MythicMob.java:703) [%5BM%5D%5B怪物%5DMythicMobs-4.7.2.jar:?]
        at io.lumine.xikage.mythicmobs.mobs.MobManager.spawnMob(MobManager.java:524) [%5BM%5D%5B怪物%5DMythicMobs-4.7.2.jar:?]
        at io.lumine.xikage.mythicmobs.mobs.MobManager.spawnMob(MobManager.java:513) [%5BM%5D%5B怪物%5DMythicMobs-4.7.2.jar:?]
        at io.lumine.xikage.mythicmobs.commands.mobs.SpawnCommand.onCommand(SpawnCommand.java:129) [%5BM%5D%5B怪物%5DMythicMobs-4.7.2.jar:?]
        at io.lumine.utils.commands.Command.onCommand(Command.java:69) [%5BM%5D%5B怪物%5DMythicMobs-4.7.2.jar:?]
        at io.lumine.utils.commands.Command.onCommand(Command.java:60) [%5BM%5D%5B怪物%5DMythicMobs-4.7.2.jar:?]
        at io.lumine.utils.commands.Command.onCommand(Command.java:66) [%5BM%5D%5B怪物%5DMythicMobs-4.7.2.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
        at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1401) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1236) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_171]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_171]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]
Caused by: java.lang.NoSuchMethodError: io.lumine.xikage.mythicmobs.api.bukkit.events.MythicMobSpawnEvent.getMob()Lio/lumine/xikage/mythicmobs/mobs/ActiveMob;
        at github.saukiya.sxitem.helper.MythicMobsHelper$V4Listener.on(MythicMobsHelper.java:172) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_171]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_171]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_171]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
        ... 26 more

**Comment by Saukiya** [comment]
Mythicmobs版本还能往上升一升不，4.7.2内好像没有这个API，看能不能换成4.12.0
MythicMobSpawnEvent.getMob() -> ActiveMob

**Comment by Saukiya** [comment]
最少也要到4.9.0才支持
