### ISSUE TITLE
1.12.2 Mythicmobs4.4 SX-item3.2.5出现如下报错 不明白问题出在那里 作者可以解答一下吗~

### ISSUE THREAD

**Issue by Fy-MoMing** [Saukiya/SX-Item#14]
Could not pass event MythicMobSpawnEvent to SX-Item v3.2.5
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[Spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[Spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) ~[Spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) ~[Spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
	at io.lumine.xikage.mythicmobs.mobs.MythicMob.spawn(MythicMob.java:726) ~[?:?]
	at io.lumine.xikage.mythicmobs.mobs.MobManager.spawnMob(MobManager.java:436) ~[?:?]
	at io.lumine.xikage.mythicmobs.spawning.spawners.MythicSpawner.Spawn(MythicSpawner.java:649) ~[?:?]
	at io.lumine.xikage.mythicmobs.spawning.spawners.MythicSpawner.tickSpawnerClock(MythicSpawner.java:511) ~[?:?]
	at io.lumine.xikage.mythicmobs.spawning.spawners.SpawnerManager.lambda$tickSpawnerClocks$1(SpawnerManager.java:210) ~[?:?]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) [?:1.8.0_211]
	at java.util.stream.ReferencePipeline$Head.forEach(Unknown Source) [?:1.8.0_211]
	at io.lumine.xikage.mythicmobs.spawning.spawners.SpawnerManager.tickSpawnerClocks(SpawnerManager.java:207) [%5B神话怪物%5DMythicMobs-4.4.0.jar:?]
	at io.lumine.xikage.mythicmobs.clock.MythicMobsClock.run(MythicMobsClock.java:49) [%5B神话怪物%5DMythicMobs-4.4.0.jar:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) [Spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361) [Spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [Spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [Spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [Spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [Spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
Caused by: java.lang.NoSuchMethodError: io.lumine.xikage.mythicmobs.api.bukkit.events.MythicMobSpawnEvent.getMob()Lio/lumine/xikage/mythicmobs/mobs/ActiveMob;
	at github.saukiya.sxitem.helper.MythicMobsHelper$V4Listener.on(MythicMobsHelper.java:172) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor266.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_211]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_211]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[Spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
	... 19 more

**Comment by Saukiya** [comment]
鸽一会

**Comment by Saukiya** [comment]
MythicMobs版本太老了，都没有这个API，最少也要到4.9.0才支持
报错相关：MythicMobs不存在该方法MythicMobSpawnEvent.getMob() -> ActiveMob

**Comment by Saukiya** [comment]
已进行V4向下兼容 [4.1.0](https://github.com/Saukiya/SX-Item/releases/tag/4.1.0)
