### ISSUE TITLE
BUG #MythicMob版本不得低于4.9.0 

### ISSUE THREAD

**Issue by dwdddfly** [Saukiya/SX-Item#16]
[14:39:43] [Server thread/ERROR]: Could not pass event MythicMobSpawnEvent to SX-Item v3.2.2
org.bukkit.event.EventException: null
        at catserver.server.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[MethodHandleEventExecutor.class:git-CatServer-1.12.2-fed56812]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:git-CatServer-1.12.2-fed56812]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:503) ~[SimplePluginManager.class:git-CatServer-1.12.2-fed56812]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:488) ~[SimplePluginManager.class:git-CatServer-1.12.2-fed56812]
        at io.lumine.xikage.mythicmobs.mobs.MythicMob.spawn(MythicMob.java:703) ~[MythicMobs-4.7.2.jar:?]
        at io.lumine.xikage.mythicmobs.mobs.MobManager.spawnMob(MobManager.java:524) ~[MythicMobs-4.7.2.jar:?]
        at io.lumine.xikage.mythicmobs.spawning.spawners.MythicSpawner.Spawn(MythicSpawner.java:650) ~[MythicMobs-4.7.2.jar:?]
        at io.lumine.xikage.mythicmobs.spawning.spawners.MythicSpawner.tickSpawnerClock(MythicSpawner.java:512) ~[MythicMobs-4.7.2.jar:?]
        at io.lumine.xikage.mythicmobs.spawning.spawners.SpawnerManager.lambda$tickSpawnerClocks$112(SpawnerManager.java:212) ~[MythicMobs-4.7.2.jar:?]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) [?:1.8.0_144]
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580) [?:1.8.0_144]
        at io.lumine.xikage.mythicmobs.spawning.spawners.SpawnerManager.tickSpawnerClocks(SpawnerManager.java:209) [MythicMobs-4.7.2.jar:?]
        at io.lumine.xikage.mythicmobs.clock.MythicMobsClock.run(MythicMobsClock.java:51) [MythicMobs-4.7.2.jar:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) [CraftTask.class:git-CatServer-1.12.2-fed56812]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:421) [CraftScheduler.class:git-CatServer-1.12.2-fed56812]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:894) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:475) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:828) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:687) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
Caused by: java.lang.NoSuchMethodError: io.lumine.xikage.mythicmobs.api.bukkit.events.MythicMobSpawnEvent.getMob()Lio/lumine/xikage/mythicmobs/mobs/ActiveMob;
        at github.saukiya.sxitem.helper.MythicMobsHelper$V4Listener.on(MythicMobsHelper.java:172) ~[SX-Item-3.2.2-all.jar:?]
        at catserver.server.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:35) ~[MethodHandleEventExecutor.class:git-CatServer-1.12.2-fed56812]
        ... 19 more

**Comment by Saukiya** [comment]
看看你用的Mythicmobs版本是多少，还不升级

**Comment by Saukiya** [comment]
已进行V4向下兼容 [4.1.0](https://github.com/Saukiya/SX-Item/releases/tag/4.1.0)
