### ISSUE TITLE
[3.1.7] MM生成怪物时存在Map并发问题

### ISSUE THREAD

**Issue by Saukiya** [Saukiya/SX-Item#5]
日志内容:
[15:30:45] [Server thread/ERROR]: Could not pass event MythicMobSpawnEvent to SX-Item v3.1.6
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at io.lumine.xikage.mythicmobs.mobs.MythicMob.spawn(MythicMob.java:753) ~[?:?]
        at io.lumine.xikage.mythicmobs.mobs.MythicMob.spawn(MythicMob.java:711) ~[?:?]
        at io.lumine.xikage.mythicmobs.mobs.MobManager.spawnMob(MobManager.java:526) ~[?:?]
        at io.lumine.xikage.mythicmobs.spawning.random.RandomSpawner.spawn(RandomSpawner.java:232) ~[?:?]
        at io.lumine.xikage.mythicmobs.spawning.random.RandomSpawnerManager.handleSpawnEvent(RandomSpawnerManager.java:169) ~[?:?]
        at io.lumine.xikage.mythicmobs.adapters.bukkit.listeners.MobListeners.lambda$load$3(MobListeners.java:144) ~[?:?]
        at io.lumine.xikage.mythicmobs.utils.Delegates$ConsumerToBiConsumerSecond.accept(Delegates.java:144) ~[?:?]
        at io.lumine.xikage.mythicmobs.utils.events.functional.single.EventListener.execute(EventListener.java:131) ~[?:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.event.CraftEventFactory.callCreatureSpawnEvent(CraftEventFactory.java:692) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3645-Spigot-19641c7-7cd3244]
        at org.bukkit.craftbukkit.v1_19_R2.event.CraftEventFactory.doEntityAddEventCalling(CraftEventFactory.java:611) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3645-Spigot-19641c7-7cd3244]
        at net.minecraft.server.level.WorldServer.addEntity(WorldServer.java:1062) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3645-Spigot-19641c7-7cd3244]
        at net.minecraft.server.level.WorldServer.addFreshEntity(WorldServer.java:999) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3645-Spigot-19641c7-7cd3244]
        at net.minecraft.world.level.WorldAccess.lambda$0(WorldAccess.java:16) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3645-Spigot-19641c7-7cd3244]
        at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
        at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:734) ~[?:?]
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
        at net.minecraft.world.level.WorldAccess.addFreshEntityWithPassengers(WorldAccess.java:16) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3645-Spigot-19641c7-7cd3244]
        at net.minecraft.world.level.SpawnerCreature.a(SpawnerCreature.java:230) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3645-Spigot-19641c7-7cd3244]
        at net.minecraft.world.level.SpawnerCreature.a(SpawnerCreature.java:159) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3645-Spigot-19641c7-7cd3244]
        at net.minecraft.world.level.SpawnerCreature.a(SpawnerCreature.java:147) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3645-Spigot-19641c7-7cd3244]
        at net.minecraft.server.level.ChunkProviderServer.t(ChunkProviderServer.java:446) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3645-Spigot-19641c7-7cd3244]
        at net.minecraft.server.level.ChunkProviderServer.a(ChunkProviderServer.java:386) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3645-Spigot-19641c7-7cd3244]
        at net.minecraft.server.level.WorldServer.a(WorldServer.java:380) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3645-Spigot-19641c7-7cd3244]
        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1294) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3645-Spigot-19641c7-7cd3244]
        at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:388) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3645-Spigot-19641c7-7cd3244]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1201) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3645-Spigot-19641c7-7cd3244]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1017) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3645-Spigot-19641c7-7cd3244]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:301) ~[spigot-1.19.3-R0.1-SNAPSHOT.jar:3645-Spigot-19641c7-7cd3244]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.util.ConcurrentModificationException
        at java.util.HashMap.computeIfAbsent(HashMap.java:1221) ~[?:?]
        at github.saukiya.sxitem.data.random.randoms.LockStringRandom.replace(LockStringRandom.java:11) ~[?:?]
        at github.saukiya.sxitem.data.random.RandomDocker.lookup(RandomDocker.java:150) ~[?:?]
        at org.apache.commons.lang.text.StrSubstitutor.resolveVariable(StrSubstitutor.java:726) ~[commons-lang-2.6.jar:2.6]
        at org.apache.commons.lang.text.StrSubstitutor.substitute(StrSubstitutor.java:649) ~[commons-lang-2.6.jar:2.6]
        at org.apache.commons.lang.text.StrSubstitutor.substitute(StrSubstitutor.java:563) ~[commons-lang-2.6.jar:2.6]
        at org.apache.commons.lang.text.StrSubstitutor.replace(StrSubstitutor.java:305) ~[commons-lang-2.6.jar:2.6]
        at github.saukiya.sxitem.data.random.RandomDocker.replace(RandomDocker.java:89) ~[?:?]
        at github.saukiya.sxitem.data.item.sub.GeneratorDefault.getItem(GeneratorDefault.java:106) ~[?:?]
        at github.saukiya.sxitem.data.item.sub.GeneratorDefault.getItem(GeneratorDefault.java:102) ~[?:?]
        at github.saukiya.sxitem.data.item.ItemManager.getItem(ItemManager.java:265) ~[?:?]
        at github.saukiya.sxitem.helper.MythicMobsHelper.lambda$static$1(MythicMobsHelper.java:103) ~[?:?]
        at github.saukiya.sxitem.helper.MythicMobsHelper$V4Listener.on(MythicMobsHelper.java:182) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        ... 35 more

**Comment by Saukiya** [comment]
https://github.com/Saukiya/SX-Item/commit/2407710c6bf7fa9119e561cb94f998a1b021359d
